name: ESLint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Change location
      run: cd /home/runner/work/aulix-frontend/aulix-frontend/aulix-marketplace
      working-directory: aulix-marketplace

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: ./node_modules/.bin/eslint ./ .
